achievementData = {
	cardPath = "images/system/banner",
	iconPath = "images/system/icon",
	keyedAchievements = {"arcade1000", "arcade5000", "arcade10000", "arcade25000", "daily", "chill", "mission1", "mission50", "missioncommand", "swaps1000", "swaps2500", "swaps5000", "swaps10000", "hexas250", "hexas500", "hexas1000", "hexas2500"},
	achievements = {
		{
			id = "arcade1000",
			name = "HEXA Rookie",
			description = "Score 1,000 points in Arcade Mode",
			isSecret = false,
			progressMax = 1000,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/score",
			iconLocked = "images/system/cheevos/unscore",
		},
		{
			id = "arcade5000",
			name = "HEXA Novice",
			description = "Score 5,000 points in Arcade Mode",
			isSecret = false,
			progressMax = 5000,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/score",
			iconLocked = "images/system/cheevos/unscore",
		},
		{
			id = "arcade10000",
			name = "HEXA Expert",
			description = "Score 10,000 points in Arcade Mode",
			isSecret = false,
			progressMax = 10000,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/score",
			iconLocked = "images/system/cheevos/unscore",
		},
		{
			id = "arcade25000",
			name = "HEXA Master",
			description = "Score 25,000 points in Arcade Mode",
			isSecret = false,
			progressMax = 25000,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/score",
			iconLocked = "images/system/cheevos/unscore",
		},
		{
			id = "daily",
			name = "Checking In",
			description = "Play a Daily Run",
			isSecret = false,
			scoreValue = 1,
			icon = "images/system/cheevos/hexa",
			iconLocked = "images/system/cheevos/unhexa",
		},
		{
			id = "chill",
			name = "Take a Chill Pill",
			description = "Play around in Chill Mode",
			isSecret = false,
			scoreValue = 1,
			icon = "images/system/cheevos/hexa",
			iconLocked = "images/system/cheevos/unhexa",
		},
		{
			id = "mission1",
			name = "Modus Operandi",
			description = "Complete a Mission",
			isSecret = false,
			scoreValue = 1,
			icon = "images/system/cheevos/mission",
			iconLocked = "images/system/cheevos/unmission",
		},
		{
			id = "mission50",
			name = "Mission Accomplished",
			description = "Complete all 50 Missions",
			progressMax = 50,
			progressIsPercentage = true,
			isSecret = false,
			scoreValue = 1,
			icon = "images/system/cheevos/mission",
			iconLocked = "images/system/cheevos/unmission",
		},
		{
			id = "missioncommand",
			name = "Mission Command",
			description = "Create a custom Mission",
			isSecret = false,
			scoreValue = 1,
			icon = "images/system/cheevos/mission",
			iconLocked = "images/system/cheevos/unmission",
		},
		{
			id = "swaps1000",
			name = "Swap Meet",
			description = "Reach 1,000 Swaps (all-time)",
			isSecret = false,
			progressMax = 1000,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/swap",
			iconLocked = "images/system/cheevos/unswap",
		},
		{
			id = "swaps2500",
			name = "Swap Machina",
			description = "Reach 2,500 Swaps (all-time)",
			isSecret = false,
			progressMax = 2500,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/swap",
			iconLocked = "images/system/cheevos/unswap",
		},
		{
			id = "swaps5000",
			name = "The Swapper",
			description = "Reach 5,000 Swaps (all-time)",
			isSecret = false,
			progressMax = 5000,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/swap",
			iconLocked = "images/system/cheevos/unswap",
		},
		{
			id = "swaps10000",
			name = "Swapped Out",
			description = "Reach 10,000 Swaps (all-time)",
			isSecret = false,
			progressMax = 10000,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/swap",
			iconLocked = "images/system/cheevos/unswap",
		},
		{
			id = "hexas250",
			name = "HEXA-spawn",
			description = "Reach 250 HEXAs (all-time)",
			isSecret = false,
			progressMax = 250,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/hexa",
			iconLocked = "images/system/cheevos/unhexa",
		},
		{
			id = "hexas500",
			name = "HEXA-gone",
			description = "Reach 500 HEXAs (all-time)",
			isSecret = false,
			progressMax = 500,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/hexa",
			iconLocked = "images/system/cheevos/unhexa",
		},
		{
			id = "hexas1000",
			name = "HEXA-ton",
			description = "Reach 1,000 HEXAs (all-time)",
			isSecret = false,
			progressMax = 1000,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/hexa",
			iconLocked = "images/system/cheevos/unhexa",
		},
		{
			id = "hexas2500",
			name = "HEXA-god",
			description = "Reach 2,500 HEXAs (all-time)",
			isSecret = false,
			progressMax = 2500,
			progressIsPercentage = true,
			scoreValue = 1,
			icon = "images/system/cheevos/hexa",
			iconLocked = "images/system/cheevos/unhexa",
		},
	}
}